influxdb:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    PRE_CREATE_DB: db1

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
    
worker:
  build: .
  environment:
    INFLUXDB_HOST: influxdb
    INFLUXDB_USERNAME: root
    INFLUXDB_PASSWORD: root
    INFLUXDB_DATABASE: db1
  links:
    - influxdb